# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug
    homeassistant.components.mqtt.client: debug

mqtt:
  #broker: localhost
  #port: 1884
  # ... reszta konfiguracji (np. username, password) ...
  #clean_session: true
  binary_sensor:
    - name: "Okno Sypialnia"
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: >
        {% if value_json.ZbReceived['0x776D'].Contact == 1 %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: window
      payload_on: "ON"
      payload_off: "OFF"
  sensor:
    - name: "HEVO power"
      unique_id: hevo_power
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0xBF7E']['ActivePower'] }}"
      unit_of_measurement: "W"
      device_class: "power"

    - name: "HEVO volt"
      unique_id: hevo_volt
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0xBF7E']['RMSVoltage'] }}"
      unit_of_measurement: "V"
      device_class: "voltage"

    - name: "HEVO curr"
      unique_id: hevo_curr
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0xBF7E']['RMSCurrent'] / 1000 }}" # Konwersja mA na A
      unit_of_measurement: "A"
      device_class: "current"
      
    - name: "Attic fan power"
      unique_id: attic_fan_power
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0xEC78']['ActivePower'] }}"
      unit_of_measurement: "W"
      device_class: "power"

    - name: "Attic fan volt"
      unique_id: attic_fan_volt
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0xEC78']['RMSVoltage'] }}"
      unit_of_measurement: "V"
      device_class: "voltage"

    - name: "Attic fan curr"
      unique_id: attic_fan_curr
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0xEC78']['RMSCurrent'] / 1000 }}" # Konwersja mA na A
      unit_of_measurement: "A"
      device_class: "current"
      
    - name: "Temperatura Ogrod"
      unique_id: temp_garden
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: >
        {% set temp = value_json.ZbReceived['0xFC52'].Temperature | default(none) %}
        {% if temp is not none %}
          {{ temp }}
        {% else %}
          {{ this.state }}
        {% endif %}
      unit_of_measurement: "°C"
      device_class: "temperature"
      state_class: "measurement"
      expire_after: 3600

    - name: "Wilgotność Ogrod"
      unique_id: hum_garden
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: >
        {% set hum = value_json.ZbReceived['0xFC52'].Humidity | default(none) %}
        {% if hum is not none %}
          {{ hum }}
        {% else %}
          {{ this.state }}
        {% endif %}
      unit_of_measurement: "%"
      device_class: "humidity"
      state_class: "measurement"
      expire_after: 3600 # Czas w sekundach (86400s = 24 godziny)

    - name: "Temperatura Taras"
      unique_id: temp_taras
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: >
        {% set temp = value_json.ZbReceived['0x0B22'].Temperature | default(none) %}
        {% if temp is not none %}
          {{ temp }}
        {% else %}
          {{ this.state }}
        {% endif %}
      unit_of_measurement: "°C"
      device_class: "temperature"
      state_class: "measurement"
      expire_after: 3600 # Czas w sekundach (86400s = 24 godziny)

    - name: "Wilgotność Taras"
      unique_id: hum_taras
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: >
        {% set hum = value_json.ZbReceived['0x0B22'].Humidity | default(none) %}
        {% if hum is not none %}
          {{ hum }}
        {% else %}
          {{ this.state }}
        {% endif %}
      unit_of_measurement: "%"
      device_class: "humidity"
      state_class: "measurement"
      expire_after: 3600 # Czas w sekundach (86400s = 24 godziny)

    - name: "Temperatura Strych"
      unique_id: temp_attic
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: >
        {% set temp = value_json.ZbReceived['0x7B4B'].Temperature | default(none) %}
        {% if temp is not none %}
          {{ temp }}
        {% else %}
          {{ this.state }}
        {% endif %}
      unit_of_measurement: "°C"
      device_class: "temperature"
      state_class: "measurement"
      expire_after: 3600 # Czas w sekundach (86400s = 24 godziny)

    - name: "Wilgotność Strych"
      unique_id: hum_attic
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: >
        {% set hum = value_json.ZbReceived['0x7B4B'].Humidity | default(none) %}
        {% if hum is not none %}
          {{ hum }}
        {% else %}
          {{ this.state }}
        {% endif %}
      unit_of_measurement: "%"
      device_class: "humidity"
      state_class: "measurement"
      expire_after: 3600 # Czas w sekundach (86400s = 24 godziny)

    - name: "Temperatura Piotr"
      unique_id: temp_piotr
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: >
        {% set temp = value_json.ZbReceived['0x5560'].Temperature | default(none) %}
        {% if temp is not none %}
          {{ temp }}
        {% else %}
          {{ this.state }}
        {% endif %}
      unit_of_measurement: "°C"
      device_class: "temperature"
      state_class: "measurement"
      expire_after: 3600

    - name: "Wilgotność Piotr"
      unique_id: hum_piotr
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: >
        {% set hum = value_json.ZbReceived['0x5560'].Humidity | default(none) %}
        {% if hum is not none %}
          {{ hum }}
        {% else %}
          {{ this.state }}
        {% endif %}
      unit_of_measurement: "%"
      device_class: "humidity"
      state_class: "measurement"
      expire_after: 3600 # Czas w sekundach (86400s = 24 godziny)

    - name: "Akcja Przycisk"
      unique_id: action_button
      state_topic: "tele/tasmota_gateway/SENSOR"
      value_template: >
        {% if value_json.ZbReceived['0xB3FC'] is defined %}
          {% if value_json.ZbReceived['0xB3FC']['0006!01'] is defined %}
            double_click
          {% elif value_json.ZbReceived['0xB3FC']['0006!02'] is defined %}
            single_click
          {% else %}
            unknown
          {% endif %}
        {% else %}
          {{ states('sensor.akcja_przycisk') }}
        {% endif %}

    - name: "Zawór Wody - Bateria"
      unique_id: water_sw
      state_topic: "tele/tasmota_gateway/SENSOR"
      unit_of_measurement: "%"
      device_class: battery
      value_template: "{{ value_json.ZbReceived['0xC227'].BatteryPercentage }}"
      availability_topic: "tele/tasmota_gateway/LWT" # Opcjonalnie, jeśli używasz LWT

  switch:
    - name: "Fountain"
      unique_id: "fountain_0xBC28"
      command_topic: "cmnd/tasmota_gateway/ZbSend"
      state_topic: "stat/tasmota_gateway/POWER" # Dostosuj do swojego tematu
      payload_on: '{"Device":"0xBC28","Send":{"Power":1}}'
      payload_off: '{"Device":"0xBC28","Send":{"Power":0}}'
      value_template: >
        {% if value_json.ZbReceived['0xBC28'] is defined %}
          {% if value_json.ZbReceived['0xBC28'].Power == 1 %} ON {% else %} OFF {% endif %}
        {% else %}
          {{ states('switch.attic_fan') }}
        {% endif %}
      optimistic: false
      retain: false

    - name: "Attic fan"
      unique_id: "relay_fan_0xEC78"
      command_topic: "cmnd/tasmota_gateway/ZbSend"
      state_topic: "stat/tasmota_gateway/POWER" # Dostosuj do swojego tematu
      payload_on: '{"Device":"0xEC78","Send":{"Power":1}}'
      payload_off: '{"Device":"0xEC78","Send":{"Power":0}}'
      value_template: >
        {% if value_json.ZbReceived['0xEC78'] is defined %}
          {% if value_json.ZbReceived['0xEC78'].Power == 1 %} ON {% else %} OFF {% endif %}
        {% else %}
          {{ states('switch.attic_fan') }}
        {% endif %}
      optimistic: false
      retain: false
      
    - name: "HEVO"
      unique_id: "hevo_0xBF7E"
      command_topic: "cmnd/tasmota_gateway/ZbSend"
      state_topic: "stat/tasmota_gateway/POWER" # Dostosuj do swojego tematu
      payload_on: '{"Device":"0xBF7E","Send":{"Power":1}}'
      payload_off: '{"Device":"0xBF7E","Send":{"Power":0}}'
      optimistic: false
      qos: 1
      value_template: >
        {% if value_json.ZbReceived['0xBF7E'] is defined %}
          {% if value_json.ZbReceived['0xBF7E'].Power == 1 %} ON {% else %} OFF {% endif %}
        {% else %}
          {{ states('switch.hevo') }}
        {% endif %}
      optimistic: false
      retain: false
      
    - name: "Relay bedroom"
      unique_id: bedroom_0x38D7
      command_topic: "cmnd/tasmota_gateway/ZbSend"
      state_topic: "tele/tasmota_gateway/SENSOR"
      payload_on: '{"device":"0x38D7","send":{"Power":1}}'
      payload_off: '{"device":"0x38D7","send":{"Power":0}}'
      value_template: >
        {% if value_json.ZbReceived['0x38D7'] is defined %}
          {% if value_json.ZbReceived['0x38D7'].Power == 1 %} ON {% else %} OFF {% endif %}
        {% else %}
          {{ states('switch.relay_bedroom') }}
        {% endif %}
      optimistic: false
      retain: false

    - name: "Relay Zosia"
      unique_id: zosia_0x7679
      command_topic: "cmnd/tasmota_gateway/ZbSend"
      state_topic: "tele/tasmota_gateway/SENSOR"
      payload_on: '{"device":"0x7679","send":{"Power":1}}'
      payload_off: '{"device":"0x7679","send":{"Power":0}}'
      value_template: >
        {% if value_json.ZbReceived['0x7679'] is defined %}
          {% if value_json.ZbReceived['0x7679'].Power == 1 %} ON {% else %} OFF {% endif %}
        {% else %}
          {{ states('switch.relay_zosia') }}
        {% endif %}
      optimistic: false
      retain: false

    - name: "Zawór Wody - Stan"
      unique_id: water_sw_state
      command_topic: "cmnd/tasmota_gateway/ZbSend"
      state_topic: "tele/tasmota_gateway/SENSOR"
      payload_on: '{"device":"0xC227","send":{"Power":0}}'
      payload_off: '{"device":"0xC227","send":{"Power":1}}'
      value_template: "{{ 'ON' if value_json.ZbReceived['0xC227'].Power == 1 else 'OFF' }}"
      # Opcje dostępności muszą być wcięte pod 'name' (czyli wewnątrz przełącznika):
      availability_topic: "tele/tasmota_gateway/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      optimistic: false

